# 3장 텐서플로 프로그래밍 101

## 3.1 텐서와 그래프 실행

In [2]:
import tensorflow as tf

In [3]:
hello = tf.constant('Hello, TensorFlow!')
print (hello)

Tensor("Const:0", shape=(), dtype=string)


Rank 0, Shape [ ]

In [12]:
tf.constant(3)

<tf.Tensor 'Const_9:0' shape=() dtype=int32>

Rank 2, Shape [2, 3]

In [13]:
tf.constant([[1, 2, 3], [7, 8, 9]])

<tf.Tensor 'Const_10:0' shape=(2, 3) dtype=int32>

Rank 3, Shape [2, 1, 3]

In [17]:
tf.constant([[[1, 2, 3]], [[7, 8, 9]]])

<tf.Tensor 'Const_13:0' shape=(2, 1, 3) dtype=int32>

랭크가 0이면 스칼라, 1이면 벡터, 2면 행렬, 3 이상이면 n-Tensor 또는 n차원 텐서

In [18]:
a = tf.constant(10)
b = tf.constant(32)
c = tf.add(a, b)
print (c)

Tensor("Add:0", shape=(), dtype=int32)


텐서플로 프로그램의 구조가 1.그래프 생성 2. 그래프 실행 의 순서로 이루어지기 때문에 42가 출력되지 않는다.

**그래프**는 텐서들의 연산 모음이다. 텐서플로는 텐서와 텐서의 연산들을 먼저 정의하여 그래프를 만들고, 이후 필요할 때 연산을 실행하는 코들르 집어 넣어 '원하는 시점'에 실제 연산을 수행하도록 한다.

이를 **지연 실행(lazy evaluation)** 이라 한다.

실제 계산은 C++로 구현한 코어 라이브러리에서 수행하므로 파이썬으로 프로그램을 작성하지만 매우 뛰어난 성능을 얻을 수 있다. 또한 모델 구성과 실행을 분리하여 프로그램을 깔끔하게 작성할 수 있다.

In [20]:
sess = tf.Session()

print (sess.run(hello))
print (sess.run([a, b, c]))

sess.close()

b'Hello, TensorFlow!'
[10, 32, 42]


### 전체 코드

In [21]:
import tensorflow as tf

hello = tf.constant('Hello, TensorFlow!')
print (hello)

a = tf.constant(10)
b = tf.constant(32)
c = tf.add(a, b)

print (c)

sess = tf.Session()

print (sess.run(hello))
print (sess.run([a, b, c]))

sess.close()

Tensor("Const_16:0", shape=(), dtype=string)
Tensor("Add_1:0", shape=(), dtype=int32)
b'Hello, TensorFlow!'
[10, 32, 42]


## 3.2 플레이스홀더와 변수

- **플레이스홀더**는 그래프에 사용할 입력값을 나중에 받기 위해 사용하는 매개변수(parameter)라 생각하면 된다.

- **변수**는 그래프를 최적화하는 용도로 텐서플로(학습 함수)가 학습한 결과를 갱신하기 위해 사용하는 변수이다. 이 변수가 신경망의 성능을 좌우하게 된다

플레이스 홀더 사용 방법

In [24]:
X = tf.placeholder(tf.float32, [None, 3])
print (X)

Tensor("Placeholder_1:0", shape=(?, 3), dtype=float32)


텐서 모양이 (?, 3)모양이기 때문에 두번째 차원은 요소를 3개씩 가지고 있어야 한다.

In [25]:
x_data = [[1, 2, 3], [4, 5, 6]]

변수 정의 방법

In [54]:
W = tf.Variable(tf.random_normal([3, 2]))
b = tf.Variable(tf.random_normal([2, 1]))

다음처럼 직접 원하는 텐서의 형태로 데이터를 만들어서 넣어줄 수도 있다.

In [27]:
W = tf.Variable([[0.1, 0.1], [0.2, 0.2], [0.3, 0.3]])

In [28]:
expr = tf.matmul(X, W) + b

연산을 실행하고 결과 출력, 설정한 텐서들과 계산된 그래프의 결과를 확인

In [53]:
sess = tf.Session()

sess.run(tf.global_variables_initializer())
print ("=== x_data ===")
print(x_data)
print("=== W ===")
print (sess.run(W))
print ("=== b ===")
print(sess.run(b))
print("=== expr ===")
print (sess.run(expr, feed_dict={X: x_data}))

sess.close()

=== x_data ===
[[1, 2, 3], [4, 5, 6]]
=== W ===
[[ 0.47927392  1.108278  ]
 [ 1.1766564   0.7309317 ]
 [-0.5955537  -0.39615414]]
=== b ===
[[-0.7454263]
 [ 0.7154957]]
=== expr ===
[[-1.0622063 -1.0622063]
 [ 3.7151868  3.7151868]]


In [63]:
W = [[0.30424118,-1.2409244 ],[0.60567963, 0.08346787],[-1.3890462, -1.085114]]
b = [[0.7038135], [2.483267 ]]

In [70]:
import numpy as np

In [72]:
np.matmul(x_data, W) + b

array([[-1.94772466, -3.62551716],
       [-1.60564733, -8.57377525]])

In [85]:
np.matmul(np.transpose(W), np.transpose(x_data)) + b

array([[-1.94772466, -3.38510083],
       [-1.84606366, -8.57377525]])

### 전체 코드

In [93]:
import tensorflow as tf

X = tf.placeholder(tf.float32, [None, 3])
print (X)

x_data = [[1, 2, 3], [4, 5, 6]]

W = tf.Variable(tf.random_normal([3, 2]))
b = tf.Variable(tf.random_normal([2, 1]))

expr = tf.matmul(X, W) + b

sess = tf.Session()
sess.run(tf.global_variables_initializer())
print ("=== x_data ===")
print(x_data)
print("=== W ===")
print (sess.run(W))
print ("=== b ===")
print(sess.run(b))
print("=== expr ===")
print (sess.run(expr, feed_dict={X: x_data}))

sess.close()

Tensor("Placeholder_9:0", shape=(?, 3), dtype=float32)
=== x_data ===
[[1, 2, 3], [4, 5, 6]]
=== W ===
[[ 0.5856814  -1.4624101 ]
 [ 0.20143653  1.4381372 ]
 [ 1.0087619  -2.3127174 ]]
=== b ===
[[-0.6656502 ]
 [ 0.13045119]]
=== expr ===
[[  3.34919    -6.1899385]
 [  9.53293   -12.404808 ]]


## 3.3 선형 회귀 모델 구현하기

In [119]:
x_data = [1, 2, 3]
y_data = [1, 2, 3]

1. 먼저 x와 y의 상관관계를 설명하기 위한 변수들인 W와 b를 각각 -1.0부터 1.0사이의 **균등분포** 를 가진 무작위 값으로 초기화한다.

In [97]:
W = tf.Variable(tf.random_uniform([1], -1.0, 1.0))
b = tf.Variable(tf.random_uniform([1], -1.0, 1.0))

2. 다음은 자료를 입력받을 플레이스 홀더를 설정한다.

In [107]:
X = tf.placeholder(tf.float32, name="X")
Y = tf.placeholder(tf.float32, name="Y")

name 매개변수를 통해 플레이스 홀더 이름을 정할 수 있다.

이렇게 텐서에 이름을 주면 어떠한 텐서가 어떻게 사용되고 있는지 쉽게 알 수 있다. 또한 텐서보드에서도 이 이름으로 출력해주므로 디버깅이 더 수월해진다. 참고로 변수와 연산 또는 연산함수에도 이름을 지정할 수 있다.

3. X와 Y의 상관관계를 분석하기 위한 수식을 작성한다.

여기서는 W와 X가 행렬이 아니므로 tf.matmul이 아니라 기본 곱셈 연산자를 사용한다.

In [110]:
hypothesis = W*X + b

4. 다음으로 손실 함수를 작성한다.

**손실함수**는 한 쌍(x, y)의 데이터에 대한 **손실값**을 계산하는 함수이다. 손실값이란 실제로 모델로 예측한 값이 얼마나 차이가 나는가를 나타내는 값이다. 즉, 손실값이 작을수록 그 모델이 X와 Y의 관계를 잘 설명하고 있다는 뜻이며, 주어진진 X 값에 대한 Y 값을 정확하게 예측할 수 있다는 뜻이 된다. 그리고 이 손실을 전체 데이터에 대한 구한 경우 이를 **비용**이라 한다.

**학습**이란 변수들의 값을 다양하게 넣어 계산해보면서 이 손실값을 최소화하는 W와 b의 값을 구하는 것이다.

손실값으로는 '예측값과 실제값의 거리' 를 가장 많이 사용한다. 따라서 손실값은 예측값에서 실제값을 뺀 뒤 제곱하며, 그리고 비용은 모든 데이터에 대한 손실값의 평균을 내어 구한다.

In [115]:
cost = tf.reduce_mean(tf.square(hypothesis - Y))

5. **경사하강법(gradient descent)** 최적화 함수를 이용해 손실값을 최소화하는 연산 그래프를 생성한다.

In [116]:
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1)
train_op = optimizer.minimize(cost)

최적화 함수란 가중치와 편향 값을 변경해가면서 손실값을 최소화하는 가장 최적화된 가중치와 편향 값을 찾아주는 함수이다.

6. 그래프를 실행해 학습을 시키고 결과를 확인해 보자.

In [123]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(100):
        _, cost_val = sess.run([train_op, cost], feed_dict={X: x_data, Y: y_data})
        
        print (step, cost_val, sess.run(W), sess.run(b))

0 0.77638143 [0.8449479] [0.4521311]
1 0.03619907 [0.8088108] [0.42372572]
2 0.026078468 [0.81776375] [0.41545627]
3 0.024739372 [0.82166845] [0.40525952]
4 0.02356303 [0.82600737] [0.39554024]
5 0.022443766 [0.8301844] [0.38602924]
6 0.021377688 [0.83426726] [0.37674963]
7 0.020362219 [0.8382513] [0.3676928]
8 0.019395003 [0.84213966] [0.35885373]
9 0.01847372 [0.8459345] [0.35022712]
10 0.017596193 [0.8496381] [0.34180787]
11 0.016760357 [0.8532527] [0.33359104]
12 0.01596424 [0.8567804] [0.32557175]
13 0.015205936 [0.86022335] [0.31774524]
14 0.014483635 [0.86358345] [0.31010684]
15 0.013795664 [0.8668629] [0.30265212]
16 0.013140337 [0.8700633] [0.29537654]
17 0.012516171 [0.87318695] [0.2882759]
18 0.0119216405 [0.8762354] [0.28134593]
19 0.011355362 [0.8792107] [0.2745826]
20 0.010815968 [0.88211435] [0.2679818]
21 0.01030221 [0.88494825] [0.2615397]
22 0.009812838 [0.887714] [0.25525245]
23 0.009346719 [0.8904133] [0.24911635]
24 0.008902737 [0.89304763] [0.24312776]
25 0.008479

In [121]:
x_data, y_data

([1, 2, 3], [1, 2, 3])

학습에 사용되지 않았떤 값인 5와 2.5를 X값으로 넣고 결과를 확인해보자

In [126]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(1000):
        _, cost_val = sess.run([train_op, cost], feed_dict={X: x_data, Y: y_data})
        
        print (step, cost_val, sess.run(W), sess.run(b))
        
    print (f"X:5, Y: {sess.run(hypothesis, feed_dict={X: 5})}")
    print (f"X:2.5, Y: {sess.run(hypothesis, feed_dict={X: 2.5})}")

0 0.77638143 [0.8449479] [0.4521311]
1 0.03619907 [0.8088108] [0.42372572]
2 0.026078468 [0.81776375] [0.41545627]
3 0.024739372 [0.82166845] [0.40525952]
4 0.02356303 [0.82600737] [0.39554024]
5 0.022443766 [0.8301844] [0.38602924]
6 0.021377688 [0.83426726] [0.37674963]
7 0.020362219 [0.8382513] [0.3676928]
8 0.019395003 [0.84213966] [0.35885373]
9 0.01847372 [0.8459345] [0.35022712]
10 0.017596193 [0.8496381] [0.34180787]
11 0.016760357 [0.8532527] [0.33359104]
12 0.01596424 [0.8567804] [0.32557175]
13 0.015205936 [0.86022335] [0.31774524]
14 0.014483635 [0.86358345] [0.31010684]
15 0.013795664 [0.8668629] [0.30265212]
16 0.013140337 [0.8700633] [0.29537654]
17 0.012516171 [0.87318695] [0.2882759]
18 0.0119216405 [0.8762354] [0.28134593]
19 0.011355362 [0.8792107] [0.2745826]
20 0.010815968 [0.88211435] [0.2679818]
21 0.01030221 [0.88494825] [0.2615397]
22 0.009812838 [0.887714] [0.25525245]
23 0.009346719 [0.8904133] [0.24911635]
24 0.008902737 [0.89304763] [0.24312776]
25 0.008479

324 4.0684967e-09 [0.99992776] [0.00016427]
325 3.8707526e-09 [0.9999295] [0.00016031]
326 3.686073e-09 [0.99993116] [0.00015645]
327 3.512871e-09 [0.9999328] [0.0001527]
328 3.3438379e-09 [0.99993443] [0.00014903]
329 3.1856e-09 [0.99993604] [0.00014546]
330 3.0404597e-09 [0.99993753] [0.00014194]
331 2.8941685e-09 [0.9999391] [0.00013855]
332 2.7488578e-09 [0.9999405] [0.0001352]
333 2.618421e-09 [0.99994195] [0.00013195]
334 2.4970366e-09 [0.9999434] [0.00012879]
335 2.374449e-09 [0.9999447] [0.00012568]
336 2.265305e-09 [0.99994606] [0.00012268]
337 2.1595241e-09 [0.9999473] [0.00011971]
338 2.055496e-09 [0.9999486] [0.00011685]
339 1.954793e-09 [0.9999498] [0.00011403]
340 1.871835e-09 [0.99995106] [0.00011131]
341 1.7757742e-09 [0.99995226] [0.00010864]
342 1.6926123e-09 [0.9999534] [0.00010601]
343 1.6067361e-09 [0.99995446] [0.00010343]
344 1.5361744e-09 [0.9999556] [0.00010095]
345 1.4640212e-09 [0.99995667] [9.853477e-05]
346 1.3929716e-09 [0.9999577] [9.615853e-05]
347 1.326

612 4.7369517e-15 [0.99999994] [1.7123837e-07]
613 4.7369517e-15 [0.99999994] [1.6329108e-07]
614 4.7369517e-15 [0.99999994] [1.5534378e-07]
615 4.7369517e-15 [0.99999994] [1.4739649e-07]
616 4.7369517e-15 [0.99999994] [1.394492e-07]
617 4.7369517e-15 [0.99999994] [1.315019e-07]
618 4.7369517e-15 [0.99999994] [1.2355461e-07]
619 4.7369517e-15 [0.99999994] [1.1560733e-07]
620 1.8947807e-14 [1.] [1.315019e-07]
621 4.2632564e-14 [0.99999994] [9.176547e-08]
622 1.8947807e-14 [1.] [1.0766004e-07]
623 4.7369517e-15 [1.] [9.971276e-08]
624 4.7369517e-15 [1.] [9.176547e-08]
625 4.7369517e-15 [1.] [8.3818186e-08]
626 4.7369517e-15 [1.] [7.58709e-08]
627 4.7369517e-15 [1.] [6.7923615e-08]
628 4.7369517e-15 [1.] [5.997633e-08]
629 4.7369517e-15 [1.] [5.2029044e-08]
630 0.0 [1.] [5.2029044e-08]
631 0.0 [1.] [5.2029044e-08]
632 0.0 [1.] [5.2029044e-08]
633 0.0 [1.] [5.2029044e-08]
634 0.0 [1.] [5.2029044e-08]
635 0.0 [1.] [5.2029044e-08]
636 0.0 [1.] [5.2029044e-08]
637 0.0 [1.] [5.2029044e-08]
638

902 0.0 [1.] [5.2029044e-08]
903 0.0 [1.] [5.2029044e-08]
904 0.0 [1.] [5.2029044e-08]
905 0.0 [1.] [5.2029044e-08]
906 0.0 [1.] [5.2029044e-08]
907 0.0 [1.] [5.2029044e-08]
908 0.0 [1.] [5.2029044e-08]
909 0.0 [1.] [5.2029044e-08]
910 0.0 [1.] [5.2029044e-08]
911 0.0 [1.] [5.2029044e-08]
912 0.0 [1.] [5.2029044e-08]
913 0.0 [1.] [5.2029044e-08]
914 0.0 [1.] [5.2029044e-08]
915 0.0 [1.] [5.2029044e-08]
916 0.0 [1.] [5.2029044e-08]
917 0.0 [1.] [5.2029044e-08]
918 0.0 [1.] [5.2029044e-08]
919 0.0 [1.] [5.2029044e-08]
920 0.0 [1.] [5.2029044e-08]
921 0.0 [1.] [5.2029044e-08]
922 0.0 [1.] [5.2029044e-08]
923 0.0 [1.] [5.2029044e-08]
924 0.0 [1.] [5.2029044e-08]
925 0.0 [1.] [5.2029044e-08]
926 0.0 [1.] [5.2029044e-08]
927 0.0 [1.] [5.2029044e-08]
928 0.0 [1.] [5.2029044e-08]
929 0.0 [1.] [5.2029044e-08]
930 0.0 [1.] [5.2029044e-08]
931 0.0 [1.] [5.2029044e-08]
932 0.0 [1.] [5.2029044e-08]
933 0.0 [1.] [5.2029044e-08]
934 0.0 [1.] [5.2029044e-08]
935 0.0 [1.] [5.2029044e-08]
936 0.0 [1.] [

전체 코드

In [129]:
import tensorflow as tf

x_data = [1, 2, 3]
y_data = [1, 2, 3]

W = tf.Variable(tf.random_uniform([1], -1.0, 1.0))
b = tf.Variable(tf.random_uniform([1], -1.0, 1.0))

X = tf.placeholder(tf.float32, name="X")
Y = tf.placeholder(tf.float32, name="Y")

hypothesis = W * X + b

cost = tf.reduce_mean(tf.square(hypothesis - Y))
optimizer = tf.train.GradientDescentOptimizer(learning_rate=0.1)
train_op = optimizer.minimize(cost)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    
    for step in range(100):
        _, cost_val = sess.run([train_op, cost], feed_dict={X: x_data,
                                                            Y: y_data})
        
        print (step, cost_val, sess.run(W), sess.run(b))
        
    print ("\n=== Test ===")
    print (f"X: 5, Y: {sess.run(hypothesis, feed_dict={X: 5})}")
    print (f"X: 2.5, Y: {sess.run(hypothesis, feed_dict={X: 2.5})}")

0 0.39755294 [0.78098166] [0.5661753]
1 0.048398864 [0.75892866] [0.54054755]
2 0.04215472 [0.76770955] [0.5288666]
3 0.04010522 [0.77296734] [0.51600945]
4 0.038199637 [0.77846074] [0.5036206]
5 0.03638511 [0.7837825] [0.4915122]
6 0.034656774 [0.7889806] [0.47969675]
7 0.033010554 [0.7940533] [0.46816516]
8 0.031442538 [0.79900414] [0.4569108]
9 0.029948981 [0.8038359] [0.44592696]
10 0.028526397 [0.8085516] [0.4352072]
11 0.027171372 [0.81315386] [0.4247451]
12 0.025880696 [0.81764555] [0.41453454]
13 0.024651362 [0.82202923] [0.40456942]
14 0.023480387 [0.8263075] [0.39484385]
15 0.02236508 [0.83048296] [0.38535208]
16 0.021302713 [0.834558] [0.37608847]
17 0.020290822 [0.8385352] [0.36704758]
18 0.01932699 [0.8424167] [0.358224]
19 0.018408947 [0.8462049] [0.34961253]
20 0.0175345 [0.849902] [0.34120807]
21 0.016701596 [0.85351026] [0.33300567]
22 0.015908265 [0.85703176] [0.32500044]
23 0.015152604 [0.8604686] [0.31718764]
24 0.01443285 [0.8638229] [0.30956268]
25 0.013747287 [0.